// Generated by CoffeeScript 1.3.3
(function() {

  define(['jade', "jquery"], function(jade, $) {
    return {
      load: function(name, req, load, config) {
        return req(['text!' + name + '.js'], function(text) {
          return load({
            render: function(ctx, fn) {
              eval("tplFn = " + text);
              return tplFn(ctx);
            }
          });
        });
      }
    };
  });

}).call(this);
